### ISSUE TITLE
Canada, Australia getting omitted

### ISSUE THREAD

**Issue by anonym0305** [caglorithm/notebooks#4]
Hi Caglar - Thanks for updating, but looks like somewhere countries like Canada and Australia are getting omitted from the code. Is it because they report cases by province/state? How does one rectify and include them as well ? Your support on this issue is greatly appreciated.

**Comment by caglorithm** [comment]
Hi @anonym0305! You are correct, this is because the data source has changed these countries to a state level resolution and I haven't yet collected them back. This is party because the data source is a bit inconsistent: The states of "Great Britian" are outside of England, whereas the states of "Canada" are obviously inside the region of interest. So I can't just blindly pool them together because I obviously don't want to throw all of GB into a country.

I didn't realize that anyone else was looking at the notebooks. Cheers for the issue!

**Comment by anonym0305** [comment]
So how do I get Canada into the data frame. I removed this:

    # Aggregate large countries split by states
#     df = pd.concat([df, 
#                     (df.loc[~df.state.isna()]
#                      .groupby(['country', 'date', 'type'])
#                      .sum()
#                      #.rename(index=lambda x: x+' (total)', level=0)
#                      .reset_index(level=['country', 'type']))
#                    ])  
    
    # Drop states for simplicity
    df = df.loc[df.state.isnull()] 

Later, I see Canada in the data frame when I run
#hide
MIN_DEATHS = 40
get_countries_with_min_cases(df_cases, 'deaths', MIN_DEATHS)

But when I do the plot.show(), this is what I'm seeing. I don't see the plots for Canada.
---------------------------------------------------------------------------
OverflowError                             Traceback (most recent call last)
<ipython-input-31-1768f8fb393c> in <module>
     50                     f"New cases max={int(df_cases_country.new_confirmed.max())}\n" + \
     51                     f"New deaths max={int(df_cases_country.new_deaths.max())}\n" + \
---> 52                     f"Estimated max={int(df_cases_country.new_deaths.max()/FATALITY_RATE)}"
     53         plt.text(1.11, 1.75, print_str,  
     54                  transform=axs[1].transAxes, va='top', ha='left',  fontsize=14)        

OverflowError: cannot convert float infinity to integer

**Comment by anonym0305** [comment]
Hi Caglar - So, looks like that I fixed the Canada data. Thanks for the wonderful work that I could build on, btw. Is there a way to reach you, I mean email ?

**Comment by caglorithm** [comment]
Hi @anonym0305, that's great news! Can I ask you what you've changed after all? You can reach me via email caglorithm=gmail-com

**Comment by anonym0305** [comment]
Did you miss something in your email? I mean the = and - appear unusual.

**Comment by caglorithm** [comment]
No it’s just what you’d expect, by replacing the weird characters :)

**Comment by caglorithm** [comment]
You can find my email in my github profile page! Cheers
