### ISSUE TITLE
05-05-2020: [Errno 2] No such file or directory: 'mplstyles/dark.mplstyle'

### ISSUE THREAD

**Issue by Tall-Bird** [caglorithm/notebooks#5]
Hey there Caglar, thanks for the easily accessible code. I saw your post on reddit and wanted to play around with the data. I've been doing so in Jupyter Notebook (as I assume you did) but on this line I'm running into an issue on line 3:

In [3]:
#hide
import matplotlib
matplotlib.rc_file('mplstyles/dark.mplstyle')

Gives me the error: FileNotFoundError: [Errno 2] No such file or directory: 'mplstyles/dark.mplstyle'

I've copied all your code pretty much exactly and have no idea where it goes wrong. Outside of that, if I remove that (and the font from ln [4]), I can reproduce the graph perfectly.

Thanks already for placing your code online!

**Comment by caglorithm** [comment]
Hey @Tall-Bird! Thanks for writing to me, I'll try to fix that error! 

Could you maybe hit me up using telegram (same handle) or mail (see my profile)?
